packages:
  - fets-point

allowBuilds:
  core-js: true
  cpu-features: set this to true or false
  esbuild: true
  msw: true
  sharp: true
  ssh2: set this to true or false

onlyBuiltDependencies: []
