import { useState } from 'react';
import { Check, Users, X } from 'lucide-react';
import { useAllStaff } from '../../hooks/useFetsConnect';
import { useCreateGroupConversation } from '../../hooks/useChat';
import { useAuth } from '../../hooks/useAuth';
import './team-chat.css';
const CreateGroupChatModal = ({ setIsModalOpen, onCreated }: { setIsModalOpen: (open: boolean) => void; onCreated?: (id: string) => void }) => {
 const { user, profile } = useAuth();const { data: users = [], isLoading } = useAllStaff();const create = useCreateGroupConversation();const [name,setName] = useState('');const [selected,setSelected] = useState<string[]>([]);
 async function save() { if (!name.trim() || !selected.length || !profile?.id) return;try { const result = await create.mutateAsync({ name:name.trim(), memberIds:selected, createdBy:profile.id });setIsModalOpen(false);onCreated?.(result.id); } catch { /* Keep the selections if creation fails. */ } }
 return <div className="tr-modal-backdrop"><form className="tr-modal" role="dialog" aria-modal="true" aria-label="Create group chat" onSubmit={e=>{e.preventDefault();void save();}}><button type="button" className="tr-modal-close" aria-label="Close" onClick={()=>setIsModalOpen(false)}><X size={20}/></button><span className="tr-kicker">BRING THE RIGHT PEOPLE TOGETHER</span><h2>A space for your team.</h2><label>Group name<input required placeholder="What are we working on?" maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><p className="tr-note">Choose the teammates who should be part of this conversation.</p><div className="tr-group-people">{isLoading?<p>Loading teammates…</p>:users.filter((p:any)=>p.id!==profile?.id&&p.user_id!==user?.id&&p.is_active!==false).map((p:any)=><label key={p.id}><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>setSelected(prev=>prev.includes(p.id)?prev.filter(id=>id!==p.id):[...prev,p.id])}/><span className="tr-avatar small">{p.full_name.split(' ').map((s:string)=>s[0]).slice(0,2).join('')}</span><span>{p.full_name}<small>{p.branch_assigned||'FETS team'}</small></span>{selected.includes(p.id)&&<Check size={16}/>}</label>)}</div><button className="tr-primary" disabled={create.isPending||!name.trim()||!selected.length}><Users size={16}/>{create.isPending?'Creating…':`Create group · ${selected.length+1} people`}</button></form></div>;
};
export default CreateGroupChatModal;
