import { useState } from 'react';
import { useAuth } from '../../hooks/useAuth';
import { useConversations } from '../../hooks/useChat';
import { useAllStaff } from '../../hooks/useFetsConnect';
import { FetsChatPopup } from '../FetsChatPopup';
import CreateGroupChatModal from './CreateGroupChatModal';
export function TeamChatWorkspace(){
 const {user,profile}=useAuth();const {data:conversations=[],isLoading,error}=useConversations(user?.id||'');const {data:staff=[]}=useAllStaff();
 const [group,setGroup]=useState(false),[target,setTarget]=useState<any>(null),[conversation,setConversation]=useState<string|null>(null);
 return <main className="min-h-[85vh] bg-[#eff3ec] p-6 md:p-10 text-[#294b40]"><header className="max-w-6xl mx-auto mb-7 flex flex-wrap justify-between gap-4"><div><p className="text-xs tracking-widest">THE PEOPLE PART</p><h1 className="text-4xl font-serif mt-2">Team conversations.</h1><p className="mt-3">Messages, group voice and group video. One place to stay connected.</p></div><button className="rounded-xl bg-[#315e4f] px-5 py-3 text-white self-center" onClick={()=>setGroup(true)}>Create group chat</button></header><div className="max-w-6xl mx-auto grid md:grid-cols-2 gap-6"><section className="bg-white p-5 rounded-2xl"><h2 className="text-xl mb-4">Your conversations</h2>{isLoading&&<p>Loading conversations…</p>}{error&&<p role="alert">Could not load conversations: {error.message}</p>}{!isLoading&&!error&&!conversations.length&&<p>Start a conversation with a teammate or create a group.</p>}{conversations.map((c:any)=><button key={c.id} className="w-full text-left border-b py-4" onClick={()=>{setTarget(null);setConversation(c.id);}}><strong>{c.name||'Direct conversation'}</strong><p className="text-sm opacity-70">{c.is_group?'Group · voice and video available':'Direct message'} · {c.last_message_preview||'Open conversation'}</p></button>)}</section><section className="bg-white p-5 rounded-2xl"><h2 className="text-xl mb-4">Your teammates</h2>{staff.filter((s:any)=>s.id!==profile?.id&&s.user_id!==user?.id).map((s:any)=><button key={s.id} className="w-full text-left border-b py-4" onClick={()=>{setConversation(null);setTarget(s);}}><strong>{s.full_name}</strong><p className="text-sm opacity-70">{s.branch_assigned||'FETS team'}</p></button>)}</section></div>{group&&<CreateGroupChatModal setIsModalOpen={setGroup}/>} {(target||conversation)&&<FetsChatPopup key={conversation||target.id} targetUser={target} conversationId={conversation} onClose={()=>{setConversation(null);setTarget(null);}}/>}</main>;
}
