import React,{useState} from 'react';
import {ArrowRight,History} from 'lucide-react';
import {centreDate} from './operations-data';
import {clock,minutes,LANES,laneInfo,type CoverageChange,type DayPlan,type PlanRecord,type TeamMember} from './shift-plan';
import type {ShiftRepository} from './shift-repository';
const currentMinute=()=>minutes(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date()));
export default function CoverageEditor({record,plan,team,changes,repository,canManage,onSaved}:{record:PlanRecord;plan:DayPlan;team:TeamMember[];changes:CoverageChange[];repository:ShiftRepository;canManage:boolean;onSaved:(change:CoverageChange)=>void}) {
 const [open,setOpen]=useState(false);const [kind,setKind]=useState<'coverage'|'lead'>('coverage');const [block,setBlock]=useState(0);const [lane,setLane]=useState<typeof LANES[number]>('front');const [staff,setStaff]=useState('');
 const [starts,setStarts]=useState(480);const [ends,setEnds]=useState(570);const [shiftStart,setShiftStart]=useState(480);const [shiftEnd,setShiftEnd]=useState(1020);const [confirmed,setConfirmed]=useState(false);const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const name=(id:string)=>team.find(p=>p.id===id)?.name||'Assigned colleague';
 const chooseBlock=(value:number)=>{setBlock(value);setStarts(Math.max(plan.blocks[value].start,record.day===centreDate()?currentMinute()+1:480));setEnds(plan.blocks[value].end);};
 const begin=()=>{const b=Math.max(0,plan.blocks.findIndex(b=>record.day>centreDate()||b.end>currentMinute()+1));chooseBlock(b);setOpen(true);};
 const save=async()=>{setBusy(true);setError('');try{const change=await repository.change({plan_id:record.id,kind,block:kind==='coverage'?block:null,lane:kind==='coverage'?lane:null,staff_id:staff,starts,ends:kind==='lead'?1020:ends,shift_start:shiftStart,shift_end:shiftEnd,reason});onSaved(change);setOpen(false);setReason('');setConfirmed(false);}catch(e){setError(e instanceof Error?e.message:'Change could not be saved.');}finally{setBusy(false);}};
 return <section className="dw-card"><div className="dw-section-head"><div><span className="planning-eyebrow">WHEN THE DAY CHANGES</span><h2>Keep coverage clear.</h2></div>{canManage&&(record.day>centreDate()||(record.day===centreDate()&&currentMinute()<1019))&&<button className="dw-secondary" onClick={begin}>Arrange cover or acting lead</button>}</div><p className="dw-muted">Keep the published plan as the original agreement. Changes record who arranged cover, why, and exactly when responsibility transfers. Earlier checks keep their original owners.</p>
  {open&&canManage&&<div className="dw-coverage-form">
   <label>Change type<select value={kind} onChange={e=>{const v=e.target.value as typeof kind;setKind(v);if(v==='lead'){setStarts(Math.max(480,record.day===centreDate()?currentMinute()+1:480));setEnds(1020);}else chooseBlock(block);}}><option value="coverage">Duty or break cover</option><option value="lead">Acting lead for the rest of the day</option></select></label>
   {kind==='coverage'&&<><label>Rotation block<select value={block} onChange={e=>chooseBlock(Number(e.target.value))}>{plan.blocks.map((b,i)=><option key={i} value={i}>{clock(b.start)}–{clock(b.end)}</option>)}</select></label><label>Duty lane<select value={lane} onChange={e=>setLane(e.target.value as typeof lane)}>{LANES.map(l=><option key={l} value={l}>{laneInfo[l].title}</option>)}</select></label></>}
   <label>Named replacement<select value={staff} onChange={e=>{setStaff(e.target.value);const a=plan.availability.find(x=>x.staff===e.target.value);setShiftStart(a?.start??480);setShiftEnd(a?.end??1020);setConfirmed(false);}}><option value="">Choose a rostered colleague</option>{team.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
   <label>Effective from<input type="time" value={clock(starts)} onChange={e=>setStarts(minutes(e.target.value))}/></label><label>Until<input type="time" value={clock(kind==='lead'?1020:ends)} disabled={kind==='lead'} onChange={e=>setEnds(minutes(e.target.value))}/></label>
   <label>Replacement’s shift starts<input type="time" value={clock(shiftStart)} onChange={e=>{setShiftStart(minutes(e.target.value));setConfirmed(false);}}/></label><label>Replacement’s shift ends<input type="time" value={clock(shiftEnd)} onChange={e=>{setShiftEnd(minutes(e.target.value));setConfirmed(false);}}/></label>
   <label className="dw-coverage-wide">Reason and coverage arrangement<textarea value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)} placeholder="Why is the plan changing? Explain how the replacement’s other duties will be covered."/></label>
   <label className="dw-checkbox dw-coverage-wide"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirmed these shift hours, availability and the combined-duty arrangement with the colleague.</label>
   <small className="dw-coverage-wide">Changes must start in a future minute. For a break, choose only its coverage period; the previous assignment resumes afterwards. A replacement cannot cover while on their own planned break.</small>
   {error&&<div role="alert" className="dw-notice dw-error dw-coverage-wide">{error}</div>}
   <div className="dw-actions dw-coverage-wide"><button className="dw-secondary" onClick={()=>setOpen(false)} disabled={busy}>Cancel</button><button className="dw-primary" onClick={save} disabled={busy||!confirmed||!staff||reason.trim().length<5||starts>=ends}>Save audited change <ArrowRight size={14}/></button></div>
  </div>}
  {changes.length>0&&<details><summary><History size={14} style={{display:'inline',verticalAlign:'middle'}}/> Change history ({changes.length})</summary>{changes.map(c=><p key={c.id} className="dw-event-note"><strong>{c.kind==='lead'?'Acting lead':`Block ${c.block!+1} · ${laneInfo[c.lane!].title}`}: {name(c.staff_id)}</strong><br/>{clock(c.starts)}–{clock(c.ends)} · arranged by {name(c.actor_id)}<br/>{c.reason}<small>{new Date(c.created_at).toLocaleString('en-GB',{timeZone:'Asia/Kolkata'})} IST</small></p>)}</details>}
 </section>;
}
