import { useEffect, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowRight, ArrowUpRight, Building2, CalendarDays, Check, ChevronDown, Flag, LayoutGrid, List, MapPin, MessageCircle, Plus, Search, Target, Users, X } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../hooks/useAuth';
import { useAllStaff } from '../hooks/useFetsConnect';
import { toast } from 'react-hot-toast';
import './mission-workspace.css';
import MissionCommons, { MissionWorkConversation } from './MissionCommons';
export const MISSION_DISTRICTS = ['Kottayam', 'Ernakulam', 'Thrissur', 'Calicut', 'Kannur'];
export const MISSION_DEADLINE = '2026-11-30';
const columns = [{ id: 'open', name: 'Next up', note: 'Ready for someone to pick up' }, { id: 'in_progress', name: 'In motion', note: 'A little closer, every day' }, { id: 'blocked', name: 'Needs a hand', note: 'Unblock it together' }, { id: 'done', name: 'Made it happen', note: 'The small wins add up' }];
const stages = { identified: 'Shortlisted', contacted: 'In conversation', audit_in_progress: 'Site review', mou_review: 'Agreement review', pearson_approved: 'Pearson approved' };
const initials = (name = '') => name.split(' ').filter(Boolean).slice(0, 2).map(n => n[0]).join('').toUpperCase();
export function missionSummary(institutions: any[], tasks: any[]) { return { shortlisted: institutions.length, approved: institutions.filter(i => i.stage === 'pearson_approved').length, active: tasks.filter(t => t.status !== 'done').length, blocked: tasks.filter(t => t.status === 'blocked').length, done: tasks.filter(t => t.status === 'done').length }; }
export default function MissionWorkspace({ navigate, legacy }: { navigate?: (page: string) => void; legacy?: React.ReactNode }) {
  const { user, profile } = useAuth(); const qc = useQueryClient(); const { data: staff = [] } = useAllStaff();
  const [tab, setTab] = useState<'today' | 'board' | 'shortlist' | 'updates'>('today');
  const [district, setDistrict] = useState('all'); const [search, setSearch] = useState(''); const [mine, setMine] = useState(false); const [archive, setArchive] = useState(false);
  const [form, setForm] = useState<'task' | 'institution' | null>(null); const [busy, setBusy] = useState(false); const [title, setTitle] = useState(''); const [formDistrict, setFormDistrict] = useState(''); const [owner, setOwner] = useState(''); const [due, setDue] = useState(''); const [institution, setInstitution] = useState('');
  const [workDetail, setWorkDetail] = useState<any>(null); const [impact, setImpact] = useState('');
  const [detail, setDetail] = useState<any>(null); const [note, setNote] = useState('');
  const [blockedTask, setBlockedTask] = useState<any>(null); const [blocker, setBlocker] = useState('');
  const data = useQuery({ queryKey: ['mission-seven'], queryFn: async () => { const [institutions, tasks, logs] = await Promise.all([supabase.from('expansion_institutions').select('*').order('updated_at', { ascending: false }), supabase.from('mission_work_items').select('*,owner:staff_profiles(full_name),institution:expansion_institutions(name)').order('created_at', { ascending: false }), supabase.from('expansion_activity_logs').select('*,institution:expansion_institutions(name)').order('created_at', { ascending: false }).limit(80)]); for (const result of [institutions, tasks, logs]) if (result.error) throw result.error; return { institutions: institutions.data || [], tasks: tasks.data || [], logs: logs.data || [] }; } });
  useEffect(() => { const channel = supabase.channel('mission-seven-team').on('postgres_changes', { event: '*', schema: 'public', table: 'mission_work_items' }, () => qc.invalidateQueries({ queryKey: ['mission-seven'] })).on('postgres_changes', { event: '*', schema: 'public', table: 'expansion_institutions' }, () => qc.invalidateQueries({ queryKey: ['mission-seven'] })).on('postgres_changes', { event: '*', schema: 'public', table: 'expansion_activity_logs' }, () => qc.invalidateQueries({ queryKey: ['mission-seven'] })).subscribe(); return () => { void supabase.removeChannel(channel); }; }, [qc]);
  const institutions = data.data?.institutions || [], tasks = data.data?.tasks || [], logs = data.data?.logs || [];
  const stats = missionSummary(institutions, tasks);
  const filteredTasks = tasks.filter((t: any) => (district === 'all' || t.district === district) && (!mine || t.owner_id === profile?.id) && `${t.title} ${t.institution?.name || ''}`.toLowerCase().includes(search.toLowerCase()));
  const filteredInstitutions = institutions.filter((i: any) => (district === 'all' || i.district === district) && i.name.toLowerCase().includes(search.toLowerCase()));
  const days = Math.max(0, Math.ceil((Date.parse('2026-11-30T23:59:59+05:30') - Date.now()) / 86400000));
  function openForm(type: 'task' | 'institution') { setForm(type); setTitle(''); setOwner(type === 'task' ? profile?.id || '' : ''); setDue(''); setFormDistrict(district === 'all' ? '' : district); setInstitution(''); setImpact(''); }
  async function save() { if (!title.trim() || (form === 'task' && !impact.trim())) return; setBusy(true); const selectedInstitution = institutions.find((i: any) => i.id === institution); const result = form === 'task' ? await supabase.from('mission_work_items').insert({ title: title.trim(), impact: impact.trim() || null, district: selectedInstitution?.district || formDistrict || null, institution_id: institution || null, owner_id: owner || null, due_date: due || null }) : await supabase.from('expansion_institutions').insert({ name: title.trim(), district: formDistrict, stage: 'identified', assigned_staff_name: staff.find((s: any) => s.id === owner)?.full_name || null, assigned_staff_id: staff.find((s: any) => s.id === owner)?.user_id || null }); setBusy(false); if (result.error) toast.error(result.error.message); else { setForm(null); void data.refetch(); toast.success(form === 'task' ? 'Next step added to the team board' : 'Institution added to the shortlist'); } }
  async function updateTask(task: any, status: string, reason?: string) { if (status === 'blocked' && reason === undefined) { setBlockedTask(task); setBlocker(task.blocker || ''); return; } const { error } = await supabase.from('mission_work_items').update({ status, blocker: status === 'blocked' ? reason : null }).eq('id', task.id); if (error) toast.error(error.message); else { setBlockedTask(null); void data.refetch(); } }
  async function claim(task: any) { const { error, data: claimed } = await supabase.from('mission_work_items').update({ owner_id: profile?.id }).eq('id', task.id).is('owner_id', null).select('id'); if (error) toast.error(error.message); else { if (!claimed?.length) toast('A teammate already claimed this step. The board has been refreshed.'); else toast.success('This next step is yours'); void data.refetch(); } }
  async function changeStage(stage: string) { if (!detail || busy) return; setBusy(true); const { error } = await supabase.from('expansion_institutions').update({ stage, updated_at: new Date().toISOString() }).eq('id', detail.id); setBusy(false); if (error) toast.error(error.message); else { setDetail({ ...detail, stage }); void data.refetch(); toast.success('Recorded milestone updated for the team'); } }
  async function addNote() { if (!detail || !note.trim()) return; setBusy(true); const { error } = await supabase.from('expansion_activity_logs').insert({ institution_id: detail.id, staff_id: user?.id, staff_name: profile?.full_name || 'Staff', entry_type: 'note', content: note.trim() }); setBusy(false); if (error) toast.error(error.message); else { setNote(''); void data.refetch(); } }
  if (archive) return <div className="mission-archive"><button onClick={() => setArchive(false)}>← Back to our shared mission</button>{legacy}</div>;
  return <div className="mission-space"><header className="ms-topline"><span className="ms-eyebrow">ACTIONABLES / OUR SHARED PLAYGROUND</span><button onClick={() => navigate?.('fets-chat')}><MessageCircle size={15}/> Talk to the team <ArrowUpRight size={14}/></button></header>
    <section className="ms-hero"><div><div className="ms-mission-label"><span/> THE FIRST SHARED MISSION</div><h1>Seven centres.<br/><em>One team.</em></h1><p>Bring Pearson VUE closer to Kerala.<br/>Turn our shortlisted colleges and institutions into the next seven centres, together.</p><div className="ms-deadline"><CalendarDays size={16}/><strong>30 November 2026</strong><span>{days} days to go</span></div></div><div className="ms-target-art" aria-label="Target: seven Pearson VUE centres"><div className="ms-orbit ms-orbit-one"/><div className="ms-orbit ms-orbit-two"/><span className="ms-art-label">PEARSON VUE / KERALA</span><strong>07<span>centres</span></strong><div className="ms-seven-dots">{Array.from({ length: 7 }, (_, i) => <i key={i}/>)}</div><small>Our shared destination</small></div></section>
    <section className="ms-stats" aria-label="Mission progress">{[{ label: 'Institutions shortlisted', value: stats.shortlisted, icon: Building2 }, { label: 'Pearson approved', value: stats.approved, icon: Check }, { label: 'Open next steps', value: stats.active, icon: Flag }, { label: 'Need a hand', value: stats.blocked, icon: Users }].map(s => <div key={s.label}><s.icon size={17}/><strong>{data.isLoading ? '…' : data.error ? '—' : String(s.value).padStart(2, '0')}</strong><span>{s.label}</span></div>)}</section>
    {data.error && <div role="alert" className="ms-error">The mission could not be loaded. <button onClick={() => void data.refetch()}>Try again</button></div>}
    {tab !== 'today' && <div className="ms-district-strip"><span>FIVE DISTRICTS.<br/><strong>SHARED AMBITION.</strong></span><button className={district === 'all' ? 'active' : ''} onClick={() => setDistrict('all')}>All districts</button>{MISSION_DISTRICTS.map(d => <button key={d} className={district === d ? 'active' : ''} onClick={() => setDistrict(d)}><MapPin size={12}/>{d}<small>{institutions.filter((i: any) => i.district === d).length}</small></button>)}</div>}
    <div className={`ms-board-bar ${tab === 'today' ? 'mc-day-nav' : ''}`}><nav aria-label="Mission views"><button aria-pressed={tab === 'today'} onClick={() => setTab('today')}><Users size={15}/> Our working day</button><button aria-pressed={tab === 'board'} onClick={() => setTab('board')}><LayoutGrid size={15}/> Team board</button><button aria-pressed={tab === 'shortlist'} onClick={() => setTab('shortlist')}><Building2 size={15}/> The shortlist</button><button aria-pressed={tab === 'updates'} onClick={() => setTab('updates')}><List size={15}/> Field notes</button></nav><button className="ms-primary" onClick={() => openForm(tab === 'shortlist' ? 'institution' : 'task')}><Plus size={15}/>{tab === 'shortlist' ? 'Add an institution' : 'Add a next step'}</button></div>
    {tab !== 'today' && <div className="ms-filter-bar"><label><Search size={14}/><input aria-label="Search mission" placeholder="Find a next step or institution" value={search} onChange={e => setSearch(e.target.value)}/></label>{tab === 'board' && <button className={mine ? 'active' : ''} onClick={() => setMine(!mine)}><Users size={13}/>{mine ? 'My next steps' : 'Everyone’s next steps'}<ChevronDown size={12}/></button>}<span>Small steps. Shared ownership. Real progress.</span></div>}
    {tab === 'today' && <MissionCommons institutions={institutions} tasks={tasks} staff={staff} loading={data.isLoading} onTask={setWorkDetail} onInstitution={i => { setDetail(i); setNote(''); }} onAddTask={i => { openForm('task'); if (i) { setInstitution(i.id); setFormDistrict(i.district); } }} onMyWork={() => { setTab('board'); setMine(true); setDistrict('all'); setSearch(''); }}/>}
    {tab === 'board' && <section className="ms-board" aria-label="Team next steps">{columns.map(column => { const items = filteredTasks.filter((t: any) => t.status === column.id); return <div className={`ms-column ms-column-${column.id}`} key={column.id}><header><span/><h2>{column.name}</h2><small>{items.length}</small></header><p className="ms-column-note">{column.note}</p>{items.map((t: any) => <article className="ms-task" key={t.id}><div className="ms-task-district">{t.district || 'Across the mission'}</div><h3>{t.title}</h3>{t.institution && <p className="ms-task-institution"><Building2 size={12}/>{t.institution.name}</p>}{t.blocker && <p className="ms-blocker">Needs help: {t.blocker}</p>}<div className="ms-task-owner"><span className="ms-avatar">{initials(t.owner?.full_name) || '+'}</span><span>{t.owner?.full_name || 'Open for someone'}</span>{!t.owner_id && <button onClick={() => void claim(t)}>I’ll take it</button>}</div><footer>{t.due_date ? <time>{new Date(`${t.due_date}T12:00:00`).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })}</time> : <span>No date set</span>}<select aria-label={`Status for ${t.title}`} value={t.status} onChange={e => void updateTask(t, e.target.value)}>{columns.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></footer><button className="mc-task-discuss" onClick={() => setWorkDetail(t)}><MessageCircle size={14}/> Work on this together</button></article>)}{items.length === 0 && <div className="ms-column-empty"><Plus size={20}/><p>{column.id === 'open' ? 'What is our next useful step?' : column.id === 'blocked' ? 'Room to ask for help.' : column.id === 'done' ? 'Our wins will collect here.' : 'Pick something up and move it here.'}</p></div>}</div>; })}</section>}
    {tab === 'shortlist' && <section className="ms-shortlist">{filteredInstitutions.map((i: any) => <button key={i.id} className="ms-institution" onClick={() => { setDetail(i); setNote(''); }}><div><span className="ms-institution-icon"><Building2 size={21}/></span><span className={`ms-stage stage-${i.stage}`}>{stages[i.stage as keyof typeof stages] || i.stage}</span></div><h3>{i.name}</h3><p><MapPin size={13}/>{i.district}</p><footer><span>{i.assigned_staff_name || 'Owner to be assigned'}</span><ArrowUpRight size={17}/></footer></button>)}{!filteredInstitutions.length && <div className="ms-empty-wide"><Building2 size={28}/><h2>The possibilities start here.</h2><p>Add the institutions you have shortlisted. Each one gets a shared place for notes and next steps.</p><button className="ms-primary" onClick={() => openForm('institution')}>Add an institution <Plus size={15}/></button></div>}</section>}
    {tab === 'updates' && <section className="ms-updates">{logs.filter((l: any) => (district === 'all' || institutions.find((i: any) => i.id === l.institution_id)?.district === district) && `${l.content} ${l.institution?.name}`.toLowerCase().includes(search.toLowerCase())).map((l: any) => <article key={l.id}><span className="ms-avatar">{initials(l.staff_name)}</span><div><strong>{l.staff_name}</strong><span> · {l.institution?.name}</span><p>{l.content}</p><time>{new Date(l.created_at).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}</time></div></article>)}{!logs.length && <div className="ms-empty-wide"><MessageCircle size={28}/><h2>Keep the whole team in the picture.</h2><p>Open an institution in the shortlist to record a meeting, an update or a question.</p></div>}</section>}
    <footer className="ms-footer"><span><Target size={13}/> Target: 7 centres · Pearson approvals are shown separately from delivery.</span>{legacy && <button onClick={() => setArchive(true)}>Previous actionables <ArrowUpRight size={12}/></button>}</footer>
    {form && <div className="ms-modal-backdrop"><form className="ms-modal" role="dialog" aria-modal="true" aria-label={form === 'task' ? 'Add a next step' : 'Add an institution'} onSubmit={e => { e.preventDefault(); void save(); }}><button className="ms-close" type="button" onClick={() => setForm(null)} aria-label="Close"><X size={20}/></button><span className="ms-eyebrow">BUILD IT TOGETHER</span><h2>{form === 'task' ? 'One useful next step.' : 'Another possibility.'}</h2><label>{form === 'task' ? 'What needs to happen?' : 'Institution name'}<input required maxLength={2000} value={title} onChange={e => setTitle(e.target.value)}/></label>{form === 'task' && <label>Why does this matter to our mission?<textarea required maxLength={1000} value={impact} onChange={e => setImpact(e.target.value)} placeholder="Which centre milestone will this help us reach?"/></label>}{form === 'task' && <label>Related institution<select value={institution} onChange={e => setInstitution(e.target.value)}><option value="">Across the mission</option>{institutions.map((i: any) => <option key={i.id} value={i.id}>{i.name}</option>)}</select></label>}<div className="ms-form-row"><label>District<select required={form === 'institution'} value={formDistrict} onChange={e => setFormDistrict(e.target.value)}><option value="">{form === 'task' ? 'All districts' : 'Choose district'}</option>{MISSION_DISTRICTS.map(d => <option key={d}>{d}</option>)}</select></label><label>Owner<select value={owner} onChange={e => setOwner(e.target.value)}><option value="">Open for someone</option>{staff.filter((s: any) => s.is_active !== false).map((s: any) => <option key={s.id} value={s.id}>{s.full_name}</option>)}</select></label></div>{form === 'task' && <label>Due date<input type="date" value={due} onChange={e => setDue(e.target.value)}/></label>}<button className="ms-primary" disabled={busy}>{busy ? 'Saving…' : 'Add to our mission'}<ArrowRight size={16}/></button></form></div>}
    {detail && <div className="ms-modal-backdrop"><section className="ms-modal ms-detail" role="dialog" aria-modal="true" aria-label={detail.name}><button className="ms-close" onClick={() => setDetail(null)} aria-label="Close"><X size={20}/></button><span className="ms-eyebrow">{detail.district} / {stages[detail.stage as keyof typeof stages]}</span><h2>{detail.name}</h2><p className="ms-detail-owner">{detail.assigned_staff_name ? `Owned by ${detail.assigned_staff_name}` : 'Owner to be assigned'}</p>{detail.primary_contact_name && <p>{detail.primary_contact_name} · {detail.primary_contact_phone || detail.primary_contact_email}</p>}{detail.notes && <p>{detail.notes}</p>}<label>Recorded milestone<select aria-label="Recorded centre milestone" disabled={busy} value={detail.stage} onChange={e => void changeStage(e.target.value)}>{Object.entries(stages).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><p className="mc-muted">Record a stage only when it has been reached. Pearson approval does not confirm centre delivery.</p><button className="mc-inline" onClick={() => { openForm('task'); setInstitution(detail.id); setFormDistrict(detail.district); setDetail(null); }}>Plan this centre’s next step <Plus size={14}/></button><label className="ms-detail-note">A note for the team<textarea value={note} onChange={e => setNote(e.target.value)} maxLength={4000} placeholder="What happened? What do we need to know?"/></label><button className="ms-primary" disabled={busy || !note.trim()} onClick={() => void addNote()}>Post field note</button><div className="ms-detail-history">{logs.filter((l: any) => l.institution_id === detail.id).map((l: any) => <article key={l.id}><strong>{l.staff_name}</strong><p>{l.content}</p></article>)}</div></section></div>}
    {workDetail && <MissionWorkConversation task={workDetail} institutions={institutions} tasks={tasks} staff={staff} onClose={() => setWorkDetail(null)} onClaim={task => void claim(task)} onStatus={(task, status) => { if (status === 'blocked') setWorkDetail(null); void updateTask(task, status); }} onInstitution={i => { setWorkDetail(null); setDetail(i); setNote(''); }}/>}
    {blockedTask && <div className="ms-modal-backdrop"><form className="ms-modal" role="dialog" aria-modal="true" aria-label="Ask for help" onSubmit={e => { e.preventDefault(); void updateTask(blockedTask, 'blocked', blocker.trim()); }}><button className="ms-close" type="button" onClick={() => setBlockedTask(null)} aria-label="Close"><X size={20}/></button><h2>What would help?</h2><label>Tell the team what is blocking this step<textarea required value={blocker} maxLength={2000} onChange={e => setBlocker(e.target.value)}/></label><button className="ms-primary">Move to needs a hand</button></form></div>}
  </div>;
}
