import {describe,it,expect} from 'vitest';
import {createDayPlan,validatePlan,checkpoints,monday,monthWeeks,working,blockReview,validateRemainingCoverage,type TeamMember} from './shift-plan';
const team:TeamMember[]=['a','b','c'].map(id=>({id,userId:id,name:id.toUpperCase(),code:'D'}));
const valid=()=>{const plan=createDayPlan(team);plan.availability.forEach(a=>a.confirmed=true);plan.breaks.forEach(b=>{b.cover=team.find(p=>p.id!==b.staff && !plan.breaks.some(x=>x.staff===p.id&&x.start<b.end&&x.end>b.start))!.id;b.note='Lead agreed combined cover, relief requested if candidate flow increases';});return plan;};
describe('centre duty planning',()=>{
 it('matches the supplied six-block timetable and includes the lead in duty ownership',()=>{const p=valid();expect(p.blocks.map(b=>b.owners)).toEqual([{front:'a',floor:'b',control:'c'},{front:'b',floor:'c',control:'a'},{front:'c',floor:'a',control:'b'},{front:'a',floor:'b',control:'c'},{front:'b',floor:'c',control:'a'},{front:'c',floor:'a',control:'b'}]);expect(validatePlan(p,team,'a')).toEqual([]);});
 it('does not turn missing staff or uncertain shift codes into complete coverage',()=>{expect(validatePlan(createDayPlan(team.slice(0,1)),team.slice(0,1),'a').length).toBeGreaterThan(0);expect(validatePlan(createDayPlan(team),team,'a').some(s=>s.includes('confirm actual'))).toBe(true);const p=valid();p.availability[0].start=540;expect(validatePlan(p,team,'a').some(s=>s.includes('outside confirmed'))).toBe(true);});
 it('requires named, available break cover and an explicit combined-duty arrangement',()=>{const p=valid();p.breaks[0].cover=p.breaks[0].staff;p.breaks[1].note='';expect(validatePlan(p,team,'a').some(s=>s.includes('name an available'))).toBe(true);expect(validatePlan(p,team,'a').some(s=>s.includes('balance both'))).toBe(true);});
 it('generates 54 walks and 90 DVR checks, with boundaries owned by the ending block and break cover applied',()=>{const p=valid();const points=checkpoints(p);expect(points.filter(x=>x.kind==='walk')).toHaveLength(54);expect(points.filter(x=>x.kind==='dvr')).toHaveLength(90);expect(points.find(x=>x.block===0&&x.kind==='dvr'&&x.due===570)?.owner).toBe('c');const breakCheck=points.find(x=>x.block===1&&x.kind==='dvr'&&x.due===606)!;expect(breakCheck.owner).toBe(p.breaks.find(b=>b.staff==='a'&&b.start===600)!.cover);});
 it('keeps Monday weeks consistent across months and years',()=>{expect(monday('2027-01-01')).toBe('2026-12-28');expect(monthWeeks('2026-09')[0]).toBe('2026-08-31');expect(monthWeeks('2026-09')).toHaveLength(5);});
 it('does not treat leave, training or public holidays as duty availability',()=>{for(const code of ['','RD','TOIL','TRD','T','PH','leave'])expect(working(code)).toBe(false);expect(working('D')).toBe(true);});
 it('validates remaining coverage after a rostered replacement takes over',()=>{const p=valid();const relief={id:'d',userId:'d',name:'Relief',code:'D'};const changes:any[]=[{kind:'coverage',block:5,lane:'floor',staff_id:'d',starts:930,ends:1020,shift_start:480,shift_end:1020}];expect(validateRemainingCoverage(p,[team[1],team[2],relief],changes,'b',930)).toEqual([]);expect(validateRemainingCoverage(p,[team[1],team[2],relief],[],'b',930).length).toBeGreaterThan(0);});
 it('a returned update stops counting as reviewed',()=>{const rows:any[]=[{block:0,lane:'front',kind:'submit'},{block:0,lane:'front',kind:'verify'},{block:0,lane:'front',kind:'return'}];expect(blockReview(rows,0,'front')).toBe('return');});
});
