begin;
-- Requires two active staff profiles; all test records are rolled back.
select set_config('request.jwt.claim.sub',(select user_id::text from public.staff_profiles where is_active and user_id is not null order by id limit 1),true);
set local role authenticated;
do $$ declare actor_user uuid:=auth.uid(); me uuid; other_id uuid; other_user uuid; task uuid; help uuid; reply uuid; centre uuid; activity uuid; begin
 select id into me from public.staff_profiles where user_id=auth.uid();
 select id,user_id into other_id,other_user from public.staff_profiles where is_active and user_id<>auth.uid() and user_id is not null limit 1;
 if other_user is null then raise exception 'Second active staff account required for isolation test';end if;
 insert into public.expansion_institutions(name,district,stage) values('Rollback only centre','Calicut','identified') returning id into centre;
 insert into public.mission_work_items(title,impact,institution_id,owner_id) values('Rollback only task','Moves the site review forward',centre,me) returning id into task;
 if not exists(select 1 from public.mission_posts where work_item_id=task and kind='activity') then raise exception 'Task creation activity missing';end if;
 update public.mission_work_items set status='done' where id=task;
 if (select count(*) from public.mission_posts where work_item_id=task)<>2 then raise exception 'Status activity missing or duplicated';end if;
 update public.expansion_institutions set stage='contacted' where id=centre;
 if not exists(select 1 from public.mission_posts where institution_id=centre and content like '%moved to contacted') then raise exception 'Centre activity missing';end if;
 insert into public.mission_posts(author_id,kind,content,work_item_id) values(me,'help','Need a site contact',task) returning id into help;
 insert into public.mission_posts(author_id,kind,content,parent_id) values(me,'comment','A contact is available',help) returning id into reply;
 if (select reply_count from public.mission_posts where id=help)<>1 then raise exception 'Reply counter missing';end if;
 if not exists(select 1 from public.mission_posts where id=reply and work_item_id=task and institution_id=centre) then raise exception 'Reply lost its work/centre context';end if;
 begin insert into public.mission_posts(author_id,kind,content) values(me,'activity','Forged event');raise exception 'Forged activity allowed';exception when insufficient_privilege then null;end;
 begin insert into public.mission_posts(author_id,kind,content) values(other_id,'update','Forged author');raise exception 'Forged author allowed';exception when insufficient_privilege then null;end;
 insert into public.mission_visits(user_id) values(auth.uid()) on conflict(user_id) do update set last_seen_at=now();
 update public.mission_visits set last_seen_at='2020-01-01' where user_id=auth.uid();
 if exists(select 1 from public.mission_visits where user_id=auth.uid() and last_seen_at<'2026-01-01') then raise exception 'Visit watermark went backwards';end if;
 insert into public.expansion_activity_logs(institution_id,staff_id,staff_name,entry_type,content) values(centre,auth.uid(),'Rollback reviewer','note','Rollback field note');
 if not exists(select 1 from public.mission_posts where institution_id=centre and content='Rollback field note') then raise exception 'Field note missing from feed';end if;
 perform set_config('request.jwt.claim.sub',other_user::text,true);
 if exists(select 1 from public.mission_visits where user_id<>auth.uid()) then raise exception 'Other visit visible';end if;
 insert into public.mission_reactions(post_id,reaction) values(help,'help');
 begin insert into public.mission_reactions(post_id,reaction) values(help,'help');raise exception 'Duplicate reaction allowed';exception when unique_violation then null;end;
 update public.mission_posts set resolved=true where id=help;
 if exists(select 1 from public.mission_posts where id=help and resolved) then raise exception 'Another staff member resolved request';end if;
 perform set_config('request.jwt.claim.sub',actor_user::text,true);
 update public.mission_posts set resolved=true where id=help;
 begin insert into public.mission_reactions(post_id,reaction) values(help,'help');raise exception 'Resolved request accepts help';exception when raise_exception then if sqlerrm='Resolved request accepts help' then raise;end if;end;
 delete from public.mission_work_items where id=task;
 if not exists(select 1 from public.mission_posts where id=help and work_item_id is null) then raise exception 'Deleted task did not preserve conversation';end if;
 delete from public.expansion_institutions where id=centre;
 if not exists(select 1 from public.mission_posts where id=help and institution_id is null) then raise exception 'Deleted institution did not preserve conversation';end if;
 perform set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000000',true);
 if exists(select 1 from public.mission_posts) or exists(select 1 from public.mission_reactions) or exists(select 1 from public.mission_visits) then raise exception 'Nonstaff can read workplace';end if;
 begin insert into public.mission_posts(author_id,kind,content) values(me,'update','Nonstaff write');raise exception 'Nonstaff write allowed';exception when insufficient_privilege then null;end;
end $$;
rollback;
