begin;
-- Requires two active staff profiles. Nothing is committed.
select set_config('request.jwt.claim.sub',(select user_id::text from public.staff_profiles where is_active and user_id is not null order by id limit 1),true);
set local role authenticated;
do $$ declare actor uuid:=auth.uid(); me uuid; colleague uuid; colleague_user uuid; centre uuid; other_centre uuid; first_stage uuid; foreign_stage uuid; task uuid; extra_task uuid; first_result uuid; last_result uuid; total integer;begin
 select id into me from public.staff_profiles where user_id=actor;
 select id,user_id into colleague,colleague_user from public.staff_profiles where is_active and user_id<>actor and user_id is not null limit 1;
 if colleague_user is null then raise exception 'Two active staff accounts are required';end if;
 select count(*) into total from public.mission_posts;
 insert into public.expansion_institutions(name,district,address,primary_contact_name,primary_contact_phone) values('Rollback institution','Calicut','Full address, Calicut, Kerala, 673001','Office','0000000000') returning id into centre;
 if (select count(*) from public.mission_institution_stages where institution_id=centre)<>7 then raise exception 'Seven starting stages were not created';end if;
 select id into first_stage from public.mission_institution_stages where institution_id=centre and stage_key='identify';
 insert into public.expansion_institutions(name,district) values('Other rollback institution','Kannur') returning id into other_centre;
 select id into foreign_stage from public.mission_institution_stages where institution_id=other_centre limit 1;
 begin
  insert into public.mission_work_items(title,institution_id,institution_stage_id,owner_id) values('Wrong context',centre,foreign_stage,me);
  raise exception 'Cross-institution stage accepted';
 exception when raise_exception then if sqlerrm='Cross-institution stage accepted' then raise;end if;end;
 insert into public.mission_work_items(title,institution_id,institution_stage_id,owner_id,due_at,report_to_id,report_instructions) values('Find the contact',centre,first_stage,colleague,'2026-10-02T20:00:00Z',actor,'Save here, then inform the project owner') returning id into task;
 if (select due_date from public.mission_work_items where id=task)<>'2026-10-03'::date then raise exception 'IST due date not preserved';end if;
 perform set_config('request.jwt.claim.sub',colleague_user::text,true);
 update public.expansion_institutions set address='Updated full address' where id=centre;
 update public.mission_work_items set title='Confirm the contact' where id=task;
 update public.mission_institution_stages set instructions='Staff edited guide' where id=first_stage;
 begin update public.mission_institution_stages set completion_note='Premature',completed_at=now() where id=first_stage;raise exception 'Open duties allowed stage completion';exception when raise_exception then if sqlerrm='Open duties allowed stage completion' then raise;end if;end;
 insert into public.mission_task_updates(work_item_id,content,status,follow_up_at,author_id) values(task,'Called the office','in_progress','2026-10-03T04:00:00Z',me) returning id into first_result;
 if not exists(select 1 from public.mission_task_updates where id=first_result and author_id=colleague and follow_up_date='2026-10-03' and report_to_id=actor) then raise exception 'Result attribution, reporting snapshot or IST follow-up incorrect';end if;
 insert into public.mission_task_updates(work_item_id,content,status,reported) values(task,'Contact confirmed','done',true) returning id into last_result;
 if (select status from public.mission_work_items where id=task)<>'done' then raise exception 'Latest outcome did not set duty status';end if;
 update public.mission_institution_stages set completion_note='Contact verified',completed_at=now() where id=first_stage;
 if not exists(select 1 from public.mission_institution_stages where id=first_stage and completed_by=colleague) then raise exception 'Stage completion actor incorrect';end if;
 perform set_config('request.jwt.claim.sub',actor::text,true);
 update public.mission_task_updates set content='Contact confirmed and recorded' where id=last_result;
 if not exists(select 1 from public.mission_task_updates where id=last_result and author_id=colleague and edited_by=me) then raise exception 'Staff cannot edit a colleague result correctly';end if;
 update public.mission_work_items set report_to_id=colleague_user where id=task;
 update public.mission_task_updates set reported=true where id=last_result;
 if (select report_to_id from public.mission_task_updates where id=last_result)<>actor then raise exception 'Historical reporting recipient changed';end if;
 delete from public.mission_task_updates where id=last_result;
 if (select status from public.mission_work_items where id=task)<>'in_progress' then raise exception 'Deleting latest result did not restore previous status';end if;
 if exists(select 1 from public.mission_institution_stages where id=first_stage and completed_at is not null) then raise exception 'Unfinished work did not reopen stage';end if;
 delete from public.mission_task_updates where id=first_result;
 if (select status from public.mission_work_items where id=task)<>'open' then raise exception 'Empty result history should restore Not started';end if;
 insert into public.mission_institution_stages(institution_id,position,title,instructions) values(centre,8,'Custom follow-up','Record the additional work');
 delete from public.mission_institution_stages where id=first_stage;
 if not exists(select 1 from public.mission_work_items where id=task and institution_stage_id is null) then raise exception 'Deleting stage lost the general follow-up duty';end if;
 perform set_config('request.jwt.claim.sub',colleague_user::text,true);
 delete from public.mission_work_items where id=task;
 if exists(select 1 from public.mission_work_items where id=task) then raise exception 'Active colleague cannot delete duty';end if;
 begin update public.mission_institution_stages set completion_note='Too early',completed_at=now() where institution_id=centre and stage_key='handover';raise exception 'Early delivery allowed';exception when raise_exception then if sqlerrm='Early delivery allowed' then raise;end if;end;
 update public.mission_institution_stages set completion_note='Evidence checked',completed_at=now() where institution_id=centre and stage_key is distinct from 'handover';
 update public.mission_institution_stages set completion_note='Owner sign-off reference',completed_at=now() where institution_id=centre and stage_key='handover';
 update public.mission_institution_stages set completed_at=null where institution_id=centre and stage_key='approach';
 if exists(select 1 from public.mission_institution_stages where institution_id=centre and stage_key='handover' and completed_at is not null) then raise exception 'Reopening an earlier stage left delivery signed off';end if;
 perform public.mission_delete_institution(centre);
 if exists(select 1 from public.mission_institution_stages where institution_id=centre) then raise exception 'Institution deletion left stages';end if;
 perform public.mission_delete_institution(other_centre);
 if (select count(*) from public.mission_posts)<>total then raise exception 'Retired feed still creates activity';end if;
 perform set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000000',true);
 if exists(select 1 from public.mission_institution_stages) or exists(select 1 from public.mission_task_updates) then raise exception 'Nonstaff can read actionables';end if;
 begin perform public.mission_delete_institution(centre);raise exception 'Nonstaff delete allowed';exception when insufficient_privilege then null;end;
end $$;
rollback;
